### ISSUE TITLE
What is the reason for unravel to wait for all Promises to settle even when one has been rejected?

### ISSUE THREAD

**Issue by semmel** [evan-king/promise-apply-spec#1]
Just out of curiosity I wonder why you made that decision. Why wait for the other Promises to become settled (or rejected) if their success value is thrown away anyway?

This behaviour is unlike `Promise.all` or `Promise.allSettled` which are the closest relatives to applySpec's  `unravel` I guess.
```javascript
unravel({
	name: (nr, s) => 
		new Promise((resolve, reject) => 
			setTimeout(resolve, 1000, s.toUpperCase())),
	number: (nr, s) => 
		Promise.reject(new Error("Stupid!"))
})([10, "test"])
.then(console.log, ex => console.error("here go the errors:", ex.message));
// 1 second elapses...
// ->  here go the errors: Promises rejected:
// - Stupid!

Promise.all([
	new Promise((resolve, reject) => setTimeout(reject, 1000, new Error("shite"))),
	Promise.reject(new Error("Stupid!"))
]).then(console.log, ex => console.error("here you don't want to go:", ex.message))
// immediately
// -> here you don't want to go: Stupid!
```

**Comment by evan-king** [comment]
Mechanisms for "racing to the first error" already exist, and by extension presume to throw out any structural metadata they might have otherwise presented.  This library's intention is to enumerate _all_ errors that occur, with adequate context to find and fix all errors in as few developer iterations (or in-flight recovery steps) as possible.

The assumption here is that if you're turning a data structure with multiple async values into a single resolved data structure, you've already assessed the appropriateness of doing so, particularly considering the likeliness/frequency of rejections in the finished product.  Additionally, accepting the cost/latency of success implies reasonable limits on the cost of unoptimized failure.

What's _not_ assumed is that a failure in one part of the data structure negates the value of work being done in other parts.  After all, the objective may not be to consolidate data but rather to process a dependency tree of operations, and it might even be crucial to know which parts did _not_ fail.  I probably wouldn't recommend such usage, but this library's only agenda is to accomplish the task its given and accurately, completely report the results.

Ultimately, however, if rejections are likely to be common or frequent in production operation, I'd likely count that as a hint that `promise-apply-spec` is the wrong tool or being abused.  I personally wouldn't use it to handle a data structure with many operations (at least containing any significant cost or complexity).  The common use-case for me is essentially a form of data templating, generally relying on no more than 2 network requests, and frequently none.

**Comment by semmel** [comment]
Thanks for your comprehensive answer!
Indeed I might have misused `promise-apply-spec` as some fancy `Promise.all` for my functional pipeline data structure. 
```javascript
R.pipe(
  _p.over(_p.lensProp("cetTime"), fetch), // both fetch requests are executed 
  _p.over(_p.lensProp("pstTime"), fetch), // sequentially
  _p.andThen(({cetTime, pstTime}) => [cetTime.dayOfTheWeek, pstTime.dayOfTheWeek])
)({ 
  cetTime: "http://worldclockapi.com/api/json/cet/now", 
  pstTime: "http://worldclockapi.com/api/json/pst/now" 
})
.then(console.log)
// -> ["Thursday", "Thursday"]
```

In a touch of over-optimisation I wanted to execute some asynchronous functions (`fetch`) of my *serial* promise pipeline in *parallel*. But`promise-apply-spec` is the wrong tool for that.

Also in my use case, the rejections which are "expected" are not *programming errors* which "need to be fixed", but more *unfortunate circumstances* which prevent this part of the program to succeed. So in a way I maybe using exceptions for flow control, but quite elegantly though 😏.

In another point perhaps, of course since Promises are not cancelable the "work being done in other parts" is not "negated" if the resulting Promise rejects, rather the result of the successful parts are thrown away. So I don't really understand that this is a good justification for waiting for all to settle. Is this different with `promise-apply-spec` ?

```javascript
Promise.all([
  new Promise(resolve => setTimeout(resolve, 1000, "test"))
  .then(R.tap(console.log))
  .then(s => s.toUpperCase()), 

  Promise.reject(new Error("oops!"))
])
.then(console.log, error => console.error("Sorry, but:", error.message))
// -> Sorry, but: oops!
// -> test  HERE WORK IS DONE after rejection nevertheless
```

**Comment by evan-king** [comment]
Indeed the wait-for-settled is not justified by desire to complete all work (at least primarily), but rather to gather all errors.  I will note however that you could collect the successful results if you retain a reference to your spec object and retry the resolution after removing all rejected promises (or in immutable context, rebuilding it with all rejected promises excluded).
